# Generated by Django 5.2.9 on 2026-03-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True, help_text='Nonbor business ID')),
                ('name', models.CharField(help_text='Printer nomi, masalan: Salat printer, Osh printer', max_length=100)),
                ('connection_type', models.CharField(choices=[('network', 'Tarmoq (IP)'), ('usb', 'USB')], default='network', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Tarmoq printerlari uchun IP manzil', null=True)),
                ('port', models.IntegerField(default=9100, help_text='TCP port (standart: 9100)')),
                ('usb_path', models.CharField(blank=True, help_text='USB printerlari uchun path, masalan: /dev/usb/lp0', max_length=200, null=True)),
                ('printer_model', models.CharField(blank=True, help_text='Printer modeli, masalan: Xprinter XP-80C', max_length=100, null=True)),
                ('paper_width', models.IntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80, help_text="Qog'oz kengligi: 58mm yoki 80mm")),
                ('is_active', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=True, help_text="Buyurtma ACCEPTED bo'lganda avtomatik chop etish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'printer',
                'ordering': ['business_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True, help_text='Nonbor order ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('printing', 'Chop etilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('content', models.TextField(blank=True, default='', help_text='Chop etish uchun matn')),
                ('items_data', models.JSONField(default=list, help_text="Taomlar ma'lumoti [{name, quantity, price, category_id}]")),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='printer.printer')),
            ],
            options={
                'db_table': 'print_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(help_text='Nonbor MenuCategory ID')),
                ('category_name', models.CharField(blank=True, default='', help_text='Kategoriya nomi (kesh)', max_length=200)),
                ('business_id', models.IntegerField(db_index=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='printer.printer')),
            ],
            options={
                'db_table': 'printer_category',
                'unique_together': {('printer', 'category_id')},
            },
        ),
    ]
