# Generated by Django 5.2.9 on 2026-03-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(help_text='Nonbor Product ID')),
                ('product_name', models.CharField(blank=True, default='', help_text='Mahsulot nomi (kesh)', max_length=300)),
                ('business_id', models.IntegerField(db_index=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='printer.printer')),
            ],
            options={
                'db_table': 'printer_product',
                'unique_together': {('business_id', 'product_id')},
            },
        ),
    ]
