# Generated by Django 5.2.9 on 2026-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_printerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('network', 'Tarmoq (IP) - lokal'), ('usb', 'USB - lokal'), ('cloud', 'Cloud - masofadan (agent orqali)')], default='network', max_length=10),
        ),
    ]
