# Generated by Django 5.2.9 on 2026-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_printer_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='is_admin',
            field=models.BooleanField(default=False, help_text="Admin printer - barcha buyurtmalar umumiy ko'rsatiladi"),
        ),
    ]
