# Generated by Django 5.2.9 on 2026-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_printer_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonborConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(help_text='Nonbor business ID', unique=True)),
                ('business_name', models.CharField(blank=True, default='', help_text='Biznes nomi (avtomatik olinadi)', max_length=200)),
                ('api_url', models.CharField(default='https://test.nonbor.uz/api/v2', help_text='Nonbor API URL', max_length=500)),
                ('api_secret', models.CharField(default='nonbor-secret-key', help_text='X-Telegram-Bot-Secret header qiymati', max_length=200)),
                ('seller_id', models.IntegerField(blank=True, help_text='Nonbor seller ID (buyurtmalarni olish uchun)', null=True)),
                ('poll_enabled', models.BooleanField(default=False, help_text='Avtomatik polling yoqilganmi')),
                ('poll_interval', models.IntegerField(default=5, help_text='Polling intervali (sekundlarda)')),
                ('last_poll_at', models.DateTimeField(blank=True, help_text='Oxirgi polling vaqti', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nonbor_config',
            },
        ),
    ]
