# Generated by Django 5.2.9 on 2026-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_add_nonbor_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(help_text='Nonbor business ID')),
                ('business_name', models.CharField(blank=True, default='', help_text="Biznes nomi (agent ekranida ko'rsatiladi)", max_length=200)),
                ('username', models.CharField(help_text='Agent login (sotuvchiga beriladi)', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Agent parol (sodda matn)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', help_text="Izoh, masalan: 'Samarqand filiali'", max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent login',
                'verbose_name_plural': 'Agent loginlar',
                'db_table': 'agent_credential',
            },
        ),
    ]
