# Generated by Django 5.2.9 on 2026-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_agentcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True, help_text='Nonbor business ID')),
                ('business_name', models.CharField(blank=True, default='', help_text='Biznes nomi (kesh)', max_length=200)),
                ('service_name', models.CharField(help_text='Servis nomi, masalan: Yandex Food, Express24', max_length=200)),
                ('api_url', models.CharField(help_text='Buyurtmalarni olish uchun API URL', max_length=500)),
                ('api_secret', models.CharField(blank=True, default='', help_text='API token yoki maxfiy kalit (ixtiyoriy)', max_length=300)),
                ('poll_enabled', models.BooleanField(default=False, help_text='Avtomatik polling yoqilganmi')),
                ('poll_interval', models.IntegerField(default=10, help_text='Polling intervali (sekundlarda)')),
                ('last_poll_at', models.DateTimeField(blank=True, help_text='Oxirgi polling vaqti', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_service',
                'ordering': ['business_id', 'service_name'],
            },
        ),
    ]
