# Generated by Django 5.2.9 on 2026-03-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_order_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shablon nomi: Nonbor, iiko, R-Keeper', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly nom: nonbor, iiko, r-keeper', unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Qisqa tavsif')),
                ('icon', models.CharField(default='🔗', help_text='Emoji yoki icon nomi', max_length=50)),
                ('color', models.CharField(default='#1890ff', help_text='Kartochka rangi (hex)', max_length=20)),
                ('base_api_url', models.CharField(blank=True, default='', help_text='Default API URL', max_length=500)),
                ('default_poll_interval', models.IntegerField(default=10, help_text='Default polling intervali (s)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Tartiblash uchun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integration_template',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderservice',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Qaysi shablon asosida yaratilgan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='printer.integrationtemplate'),
        ),
    ]
