# Generated by Django 5.2.9 on 2026-03-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_integration_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonborconfig',
            name='api_secret',
            field=models.CharField(blank=True, default='nonbor-secret-key', help_text='X-Telegram-Bot-Secret header qiymati', max_length=200),
        ),
    ]
