# Generated by Django 5.2.9 on 2026-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_alter_nonborconfig_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Telegram bot token (ixtiyoriy)', max_length=500),
        ),
    ]
