# Generated by Django 5.2.9 on 2026-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0010_add_bot_token_to_orderservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='api_url',
            field=models.CharField(blank=True, default='', help_text='Buyurtmalarni olish uchun API URL (ixtiyoriy)', max_length=500),
        ),
    ]
