# Generated by Django 5.2.9 on 2026-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0011_make_api_url_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtemplate',
            name='logo',
            field=models.ImageField(blank=True, help_text='Integratsiya logotipi', null=True, upload_to='integration_logos/'),
        ),
    ]
