# Generated by Django 5.2.9 on 2026-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0012_add_logo_to_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True, help_text='Nonbor business ID', unique=True)),
                ('business_name', models.CharField(blank=True, default='', help_text='Biznes nomi (kesh)', max_length=200)),
                ('header_text', models.CharField(blank=True, default='', help_text="Sarlavha matni (bo'sh bo'lsa business_name ishlatiladi)", max_length=200)),
                ('show_customer_info', models.BooleanField(default=True, help_text="Mijoz ma'lumotlari (ism, telefon, manzil)")),
                ('show_other_printers', models.BooleanField(default=True, help_text="Boshqa printerlar bo'limi")),
                ('show_comment', models.BooleanField(default=True, help_text='Mijoz izohi')),
                ('show_product_names', models.BooleanField(default=True, help_text='Mahsulot nomlari katta shriftda (oddiy printerlar uchun)')),
                ('footer_text', models.CharField(blank=True, default='', help_text='Chek pastida chiqadigan matn', max_length=300)),
                ('font_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Katta')], default='normal', max_length=10)),
                ('default_paper_width', models.IntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'receipt_template',
            },
        ),
    ]
