# Generated by Django 5.2.9 on 2026-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0013_receipttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemplate',
            name='template_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish'), ('dine_in', 'Zalda')], default='delivery', help_text='Buyurtma turi: delivery, pickup, dine_in', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='business_id',
            field=models.IntegerField(db_index=True, help_text='Nonbor business ID'),
        ),
        migrations.AlterUniqueTogether(
            name='receipttemplate',
            unique_together={('business_id', 'template_type')},
        ),
    ]
