# Generated by Django 5.2.9 on 2026-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0014_receipttemplate_template_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttemplate',
            name='template_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish'), ('dine_in', 'Zalda'), ('sched_del', 'Reja yetkazish'), ('sched_pick', 'Reja olib ketish')], default='delivery', help_text='Buyurtma turi: delivery, pickup, dine_in', max_length=10),
        ),
    ]
