# Generated by Django 5.2.9 on 2026-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0015_alter_receipttemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttemplate',
            name='footer_text',
            field=models.CharField(blank=True, default='Rahmat!', help_text='Chek pastida chiqadigan matn', max_length=300),
        ),
    ]
