# Generated by Django 5.2.9 on 2026-03-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0016_receipt_template_footer_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True, help_text='Nonbor business ID', unique=True)),
                ('business_name', models.CharField(blank=True, default='', help_text='Biznes nomi (kesh)', max_length=200)),
                ('telegram_bot_token', models.CharField(blank=True, default='', help_text='Telegram bot token', max_length=500)),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='Telegram chat/group ID', max_length=100)),
                ('telegram_enabled', models.BooleanField(default=False, help_text='Telegram xabar yuborish yoqilganmi')),
                ('cloud_timeout_minutes', models.IntegerField(default=5, help_text='Cloud printer javob berish vaqti (daqiqa)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_config',
            },
        ),
        migrations.CreateModel(
            name='PrinterNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('printer_name', models.CharField(blank=True, default='', max_length=100)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('print_job_id', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('error', 'Xatolik'), ('warning', 'Ogohlantirish'), ('info', "Ma'lumot")], default='error', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'printer_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
