# Generated by Django 5.2.9 on 2026-03-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0017_notification_config_and_printer_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='external_order_id',
            field=models.CharField(blank=True, default='', help_text='Tashqi tizim buyurtma ID (dublikat oldini olish uchun)', max_length=200),
        ),
        migrations.AddField(
            model_name='printjob',
            name='service_type',
            field=models.CharField(db_index=True, default='nonbor', help_text='Buyurtma manbasi: nonbor, telegram, yandex, uzum, express24, iiko, custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('network', 'Tarmoq (IP) - lokal'), ('usb', 'USB - lokal'), ('cloud', 'Cloud - masofadan (agent orqali)'), ('wifi', 'WiFi - simsiz tarmoq')], default='network', max_length=10),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='order_id',
            field=models.IntegerField(db_index=True, help_text='Buyurtma ID (platformadan)'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='template_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish'), ('dine_in', 'Zalda'), ('sched_del', 'Reja yetkazish'), ('sched_pick', 'Reja olib ketish'), ('admin', 'Admin printer')], default='delivery', help_text='Buyurtma turi: delivery, pickup, dine_in', max_length=10),
        ),
    ]
