# Generated by Django 5.1 on 2026-04-13 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0018_printjob_external_order_id_printjob_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationconfig',
            name='cloud_timeout_minutes',
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='cloud_timeout_seconds',
            field=models.IntegerField(default=20, help_text='Cloud printer javob berish vaqti (sekund). Default: 20'),
        ),
        migrations.AlterField(
            model_name='agentcredential',
            name='password',
            field=models.CharField(help_text='Agent parol (hashed)', max_length=200),
        ),
        migrations.AlterField(
            model_name='nonborconfig',
            name='api_secret',
            field=models.CharField(blank=True, default='', help_text='X-Telegram-Bot-Secret header qiymati', max_length=200),
        ),
        migrations.AlterField(
            model_name='nonborconfig',
            name='api_url',
            field=models.CharField(default='https://prod.nonbor.uz/api/v2', help_text='Nonbor API URL', max_length=500),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True, help_text="Seller bog'langan biznes ID")),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_superadmin', models.BooleanField(default=False, help_text="True bo'lsa barcha bizneslarni ko'radi (master admin)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_profile',
            },
        ),
    ]
