# Generated by Django 5.1 on 2026-04-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0019_remove_notificationconfig_cloud_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='p8_api_url',
            field=models.CharField(blank=True, default='https://api.trenditen.com', help_text='Trendit P8 bulut API manzili', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='p8_device_sn',
            field=models.CharField(blank=True, help_text='Trendit P8 qurilma seriya raqami (SN)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='p8_key',
            field=models.CharField(blank=True, help_text='Trendit P8 API kaliti (access key)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('network', 'Tarmoq (IP) - lokal'), ('usb', 'USB - lokal'), ('cloud', 'Cloud - masofadan (agent orqali)'), ('wifi', 'WiFi - simsiz tarmoq'), ('p8', 'Trendit P8 - Smart Cloud Printer')], default='network', max_length=10),
        ),
    ]
